### ISSUE TITLE
Copy/paste in the VM seems broken

### ISSUE THREAD

**Issue by alyssarosenzweig** [AsahiLinux/muvm#57] opened 2024-09-07 18:52 UTC
Not 100% sure if/how this is supposed to work. Noticed in Steam. Not a big deal (low priority versus #56) but definitely a paper cut worth writing down before I forget.

**Comment by asahilina** [comment] 2024-10-04 00:34
Duplicate of #73.

**Closed by asahilina** 2024-10-04 00:34 UTC
