### ISSUE TITLE
Drop down menus are glitchy in wine

### ISSUE THREAD

**Issue by m1m1k4tz** [AsahiLinux/muvm#42] opened 2024-07-03 21:29 UTC
The right click menu in regedit and drop down menus in winecfg are broken this happens in hangover and boxwine

**Comment by asahilina** [comment] 2024-10-04 00:35
This is fixed (it was a mesa/virglrenderer issue). Any remaining popup issues are a duplicate of #73.

**Closed by asahilina** 2024-10-04 00:35 UTC
