### ISSUE TITLE
No window decorations

### ISSUE THREAD

**Issue by m1m1k4tz** [AsahiLinux/muvm#13] opened 2024-05-28 01:55 UTC

**Comment by teohhanhui** [comment] 2024-05-28 01:59
What do you mean by toolbar?

**Comment by m1m1k4tz** [comment] 2024-05-28 02:09
The top bar where you would be able to press x also drop down boxes don’t work well

**Comment by asahilina** [comment] 2024-10-04 00:34
Duplicate of #73.

**Closed by asahilina** 2024-10-04 00:34 UTC
